<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-7PT4AIA" name="com.crm.qa.testcases.ContactsPageTests" tests="3" failures="0" timestamp="29 Jul 2018 15:48:22 GMT" time="79.146" errors="1">
  <testcase name="verifyContactsLabelTest" time="46.735" classname="com.crm.qa.testcases.ContactsPageTests"/>
  <testcase name="checkContactsListNameTest" time="32.411" classname="com.crm.qa.testcases.ContactsPageTests"/>
  <testcase name="createNewContactTest" time="0.000" classname="com.crm.qa.testcases.ContactsPageTests">
    <error type="org.testng.TestNGException" message="
Method public void com.crm.qa.testcases.ContactsPageTests.createNewContactTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : getCRMTestData">
      <![CDATA[org.testng.TestNGException: 
Method public void com.crm.qa.testcases.ContactsPageTests.createNewContactTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : getCRMTestData
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:336)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:498)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createNewContactTest -->
</testsuite> <!-- com.crm.qa.testcases.ContactsPageTests -->
